#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Climate Viewer Constants and Configuration
===========================================
climate_viewer_constants.py
Last Updated: 2025-11-28 17:15 AEST - Per-location amplification factors

Constants and settings for the Climate Metrics Viewer.

Configuration values are loaded from climate_config.json (generated by climateConfig.py).
Only true constants (EMOJI, data schema, UI layout) are hardcoded here.
"""

import os
import json

# ============================================================================
# FILE PATHS
# ============================================================================

BASE_DIR = os.path.dirname(os.path.abspath(__file__)) if "__file__" in globals() else os.getcwd()
FOLDER = os.path.join(BASE_DIR, "metricsDataFiles")
CONFIG_FILE = os.path.join(BASE_DIR, "climate_config.json")


# ============================================================================
# LOAD CONFIGURATION FROM JSON
# ============================================================================

def _load_config():
    """Load configuration from climate_config.json."""
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    else:
        print(f"[!] Config file not found: {CONFIG_FILE}")
        print("    Run: python Utilities_Scenario/climateConfig.py regenerate")
        # Return minimal defaults
        return {
            "parameters": {
                "baseline_period_start": 1850,
                "baseline_period_end": 1900,
                "amplification_factor": 1.15,
                "global_thresholds": [1.0, 1.5, 2.0, 2.5, 3.0, 4.0],
                "alignment_year": 2014
            },
            "defaults": {
                "scenarios_on": ["SSP1-26", "SSP3-70"],
                "scenarios_off": ["historical", "AGCD", "SSP2-45", "SSP5-85"],
                "start_year": 2020,
                "end_year": 2050,
                "year_buffer": 10,
                "smoothing_enabled": True,
                "smoothing_window": 20,
                "bc_enabled": True,
                "align_to_agcd": True,
                "show_15c_target": True,
                "show_time_horizons": True
            },
            "time_horizons": {
                "short_start": 2020,
                "mid_start": 2036,
                "long_start": 2039,
                "horizon_end": 2045
            },
            "scenario_info": {},
            "warming_thresholds": {},
            "alignment_offsets": {}
        }


_CONFIG = _load_config()

# ============================================================================
# APPLICATION SETTINGS
# ============================================================================

MODE = "metrics"
PORT = 8502

# ============================================================================
# CLIMATE PARAMETERS (from config)
# ============================================================================

# Baseline period for pre-industrial temperature calculations
BASELINE_PERIOD = (
    _CONFIG["parameters"]["baseline_period_start"],
    _CONFIG["parameters"]["baseline_period_end"]
)

# Regional warming amplification factor (Australia continental average)
# Calculated from ACCESS-CM2 SSP1-2.6: Regional warming / Global warming
AMPLIFICATION_FACTORS = _CONFIG["parameters"].get("amplification_factors", {})
AMPLIFICATION_FACTOR = AMPLIFICATION_FACTORS.get("Australia", 1.22)  # Default 1.22 if not calculated

# Global warming thresholds
GLOBAL_THRESHOLDS = _CONFIG["parameters"]["global_thresholds"]

# Alignment year for AGCD
ALIGNMENT_YEAR = _CONFIG["parameters"]["alignment_year"]
REFERENCE_YEAR = ALIGNMENT_YEAR  # Alias for backward compatibility

# Default target for shading (typically 1.5)
WARMING_TARGET = 1.5

# ============================================================================
# DEFAULT SETTINGS (from config)
# ============================================================================

DEFAULT_START_YEAR = _CONFIG["defaults"]["start_year"]
DEFAULT_END_YEAR = _CONFIG["defaults"]["end_year"]
YEAR_BUFFER = _CONFIG["defaults"]["year_buffer"]
DEFAULT_SCENARIOS_ON = _CONFIG["defaults"]["scenarios_on"]
DEFAULT_SMOOTHING_WINDOW = _CONFIG["defaults"]["smoothing_window"]

# ============================================================================
# TIME HORIZONS (from config)
# ============================================================================

TIME_HORIZONS = {
    'short_start_default': _CONFIG["time_horizons"]["short_start"],
    'mid_start_default': _CONFIG["time_horizons"]["mid_start"],
    'long_start_default': _CONFIG["time_horizons"]["long_start"],
    'horizon_end_default': _CONFIG["time_horizons"]["horizon_end"]
}

# ============================================================================
# WARMING THRESHOLDS (from config)
# ============================================================================

# Pre-calculated thresholds per location (from Historical raw data)
# Access: WARMING_THRESHOLDS["Ravenswood"]["thresholds"]["1.5"]
WARMING_THRESHOLDS = _CONFIG.get("warming_thresholds", {})

# ============================================================================
# SCENARIO INFO (from config)
# ============================================================================

SCENARIO_INFO = _CONFIG.get("scenario_info", {})

# ============================================================================
# EMOJI CONSTANTS (Unicode escapes - won't corrupt during file edits)
# ============================================================================

EMOJI = {
    # Navigation & UI
    "thermometer": "\U0001F321\uFE0F",
    "chart": "\U0001F4CA",
    "globe": "\U0001F30D",
    "book": "\U0001F4D6",
    "pin": "\U0001F4CD",
    "calendar": "\U0001F4C5",
    "map": "\U0001F5FA\uFE0F",
    "lightbulb": "\U0001F4A1",
    "warning": "\u26A0\uFE0F",
    "page": "\U0001F4C4",
    "search": "\U0001F50D",
    "display": "\U0001F5A5\uFE0F",
    "graph": "\U0001F4C8",
    "wrench": "\U0001F527",
    "info": "\u2139\uFE0F",
    # Status indicators
    "check": "\u2705",
    "x_mark": "\u274C",
    "green_circle": "\U0001F7E2",
    "yellow_circle": "\U0001F7E1",
    "red_circle": "\U0001F534",
    # Additional
    "wave": "\U0001F30A",
    "scroll": "\U0001F4DC",
    "link": "\U0001F517",
    "books": "\U0001F4DA",
    "gear": "\u2699\uFE0F",
}

# ============================================================================
# DATA SCHEMA
# ============================================================================

GROUP_KEYS = ["Location", "Type", "Name", "Season", "Data Type"]
IDX_COLS_ANNUAL = ["Year"]
IDX_COLS_SEASONAL = ["Year", "Season"]

REQUIRED_COLUMNS = {
    "Year": "Int64",
    "Season": str,
    "Data Type": str,
    "Value": float,
    "Location": str,
    "Name": str,
    "Type": str,
    "Scenario": str
}

# ============================================================================
# SEASONS
# ============================================================================

SEASONS = {
    'all': ['Annual', 'DJF', 'MAM', 'JJA', 'SON'],
    'names': {
        'DJF': 'Summer (Dec-Feb)',
        'MAM': 'Autumn (Mar-May)',
        'JJA': 'Winter (Jun-Aug)',
        'SON': 'Spring (Sep-Nov)',
        'Annual': 'Annual'
    }
}

# ============================================================================
# METRIC PRIORITIES
# ============================================================================

METRIC_PRIORITIES = {
    'Rain': [
        'Total',
        'Total (BC)',
        'Max Day',
        'Max Day (BC)',
        'Max 5-Day',
        'Max 5-Day (BC)',
        'R10mm',
        'R10mm (BC)',
        'R20mm',
        'R20mm (BC)',
        'Min Day',
        'Min Day (BC)',
        'Min 5-Day',
        'Min 5-Day (BC)',
        'CDD',
        'CDD (BC)'
    ],
    'Temp': [
        'Average',
        'Max Day',
        'Avg Max',
        '5-Day Avg Max',
        'Min Day',
        'Avg Min',
        '5-Day Avg Min',
        'Days >37C 3hr',
        'Days >40C 3hr'
    ],
    'Wind': [
        'Average',
        '95th Percentile',
        'Max Day'
    ],
    'Humidity': [
        'Average'
    ],
    'VPD': [
        'Average'
    ]
}

# ============================================================================
# DASHBOARD METRICS
# ============================================================================

DASHBOARD_METRICS = {
    'Temp': [
        ('Temp', 'Average', '°C', 'thermometer', 'temp_avg'),
        ('Temp', '5-Day Avg Max', '°C', 'thermometer', 'temp_max'),
        ('Temp', 'Days >37C 3hr', 'days', 'thermometer', 'temp_heat_days')
    ],
    'Rain': [
        ('Rain', 'Total', 'mm', 'wave', 'rain_total'),
        ('Rain', '5-Day', 'mm', 'wave', 'rain_5day'),
        ('Rain', 'CDD', 'days', 'warning', 'rain_cdd')
    ],
    'Wind': [
        ('Wind', 'Average', 'm/s', 'wave', 'wind_avg'),
        ('Wind', '95 Percent', 'm/s', 'wave', 'wind_95')
    ],
    'Humidity': [
        ('Humidity', 'Average', '%', 'wave', 'humidity_avg')
    ]
}

# ============================================================================
# FEATURE FLAGS
# ============================================================================

try:
    import folium
    from streamlit_folium import st_folium

    FOLIUM_AVAILABLE = True
except ImportError:
    FOLIUM_AVAILABLE = False


# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

def get_scenario_description(scenario: str) -> str:
    """
    Get description for a scenario.

    Args:
        scenario: Scenario name

    Returns:
        Description string
    """
    # Check scenario_info from config
    if scenario in SCENARIO_INFO:
        return SCENARIO_INFO[scenario].get("description", "Climate scenario")

    # Try case-insensitive match
    for key, info in SCENARIO_INFO.items():
        if key.lower() == scenario.lower():
            return info.get("description", "Climate scenario")

    # Fallback descriptions
    fallback = {
        'SSP1-26': 'Sustainability pathway, ~1.8°C by 2100',
        'SSP1-1.9': 'Very low emissions, ~1.5°C by 2100',
        'SSP2-45': 'Middle of the road, ~2.7°C by 2100',
        'SSP3-70': 'Regional rivalry, ~3.6°C by 2100',
        'SSP5-85': 'Fossil-fuelled development, ~4.4°C by 2100',
        'historical': 'Historical model simulation (1850-2014)',
        'Historical': 'Historical model simulation (1850-2014)',
        'AGCD': 'Australian Gridded Climate Data (observations)'
    }

    return fallback.get(scenario, "Climate scenario")


def get_warming_threshold(location: str, threshold: float) -> float:
    """
    Get the regional temperature for a global warming threshold.

    Args:
        location: Location name (e.g. 'Ravenswood')
        threshold: Global warming level (e.g. 1.5)

    Returns:
        Regional temperature threshold, or None if not found
    """
    if location in WARMING_THRESHOLDS:
        thresholds = WARMING_THRESHOLDS[location].get("thresholds", {})
        return thresholds.get(str(threshold))
    return None


def get_preindustrial_baseline(location: str) -> float:
    """
    Get the pre-industrial baseline temperature for a location.

    Args:
        location: Location name

    Returns:
        Pre-industrial baseline temperature, or None if not found
    """
    if location in WARMING_THRESHOLDS:
        return WARMING_THRESHOLDS[location].get("preindustrial_baseline")
    return None


def get_amplification_factor(location: str = None) -> float:
    """
    Get the regional warming amplification factor.

    Uses Australia continental average for all locations.

    Returns:
        Amplification factor (default 1.22)
    """
    return AMPLIFICATION_FACTOR


def should_use_inverse_delta(metric_type: str, metric_name: str) -> bool:
    """
    Determine if a metric should use inverse delta colouring.

    For most metrics, increases (positive deltas) are shown in red (bad).
    For some metrics like rainfall, increases might be good.

    Args:
        metric_type: Type of metric (Temp, Rain, Wind, Humidity)
        metric_name: Name of metric

    Returns:
        True if delta colours should be inverted (green=increase, red=decrease)
    """
    metric_name_lower = metric_name.lower()

    # CDD (Consecutive Dry Days) - increase is BAD, use normal colouring
    if 'cdd' in metric_name_lower or 'dry days' in metric_name_lower:
        return False

    # For rainfall totals - increase is generally GOOD
    if metric_type == 'Rain':
        if 'total' in metric_name_lower:
            return True
        return False

    # Temperature/Wind/Humidity increases generally BAD
    return False


def reload_config():
    """Reload configuration from JSON file."""
    global _CONFIG, BASELINE_PERIOD, AMPLIFICATION_FACTOR, AMPLIFICATION_FACTORS
    global GLOBAL_THRESHOLDS, ALIGNMENT_YEAR, DEFAULT_START_YEAR, DEFAULT_END_YEAR
    global YEAR_BUFFER, DEFAULT_SCENARIOS_ON, DEFAULT_SMOOTHING_WINDOW, TIME_HORIZONS
    global WARMING_THRESHOLDS, SCENARIO_INFO

    _CONFIG = _load_config()

    BASELINE_PERIOD = (
        _CONFIG["parameters"]["baseline_period_start"],
        _CONFIG["parameters"]["baseline_period_end"]
    )
    AMPLIFICATION_FACTORS = _CONFIG["parameters"].get("amplification_factors", {})
    AMPLIFICATION_FACTOR = AMPLIFICATION_FACTORS.get("Australia", 1.22)
    GLOBAL_THRESHOLDS = _CONFIG["parameters"]["global_thresholds"]
    ALIGNMENT_YEAR = _CONFIG["parameters"]["alignment_year"]

    DEFAULT_START_YEAR = _CONFIG["defaults"]["start_year"]
    DEFAULT_END_YEAR = _CONFIG["defaults"]["end_year"]
    YEAR_BUFFER = _CONFIG["defaults"]["year_buffer"]
    DEFAULT_SCENARIOS_ON = _CONFIG["defaults"]["scenarios_on"]
    DEFAULT_SMOOTHING_WINDOW = _CONFIG["defaults"]["smoothing_window"]

    TIME_HORIZONS = {
        'short_start_default': _CONFIG["time_horizons"]["short_start"],
        'mid_start_default': _CONFIG["time_horizons"]["mid_start"],
        'long_start_default': _CONFIG["time_horizons"]["long_start"],
        'horizon_end_default': _CONFIG["time_horizons"]["horizon_end"]
    }

    WARMING_THRESHOLDS = _CONFIG.get("warming_thresholds", {})
    SCENARIO_INFO = _CONFIG.get("scenario_info", {})